# Generated by Django 3.2.10 on 2023-02-04 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Полное описание курса')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание курса')),
                ('age_category', models.CharField(choices=[('FROM_8_TO_10_Y_O', '8-10 лет'), ('FROM_10_TO_12_Y_O', '10-12 лет'), ('FROM_12_TO_14_Y_O', '12-14 лет'), ('FROM_14_TO_16_Y_O', '14-16 лет')], max_length=30, verbose_name='Возрастная категория')),
                ('duration', models.CharField(max_length=30, verbose_name='Длительность курса')),
                ('is_recomended', models.BooleanField(default=False, verbose_name='Рекомендован?')),
                ('main_image', models.ImageField(default='defautl_course_image.png', upload_to='', verbose_name='Изображение курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес школы')),
                ('main_image', models.ImageField(upload_to='', verbose_name='Фото школы')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='School_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_day', models.CharField(choices=[('MONDAY', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница')], max_length=25, verbose_name='День недели')),
                ('class_time', models.CharField(choices=[('FROM_10_TO_12', 'С 10:00 до 12:00'), ('FROM_12_TO_14', 'С 12:00 до 14:00'), ('FROM_14_TO_16', 'С 14:00 до 16:00'), ('FROM_16_TO_18', 'С 16:00 до 18:00'), ('FROM_18_TO_20', 'С 18:00 до 20:00')], max_length=25, verbose_name='Время')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course', verbose_name='Курс')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Курс в школе',
                'verbose_name_plural': 'Курсы в школах',
            },
        ),
    ]
