# Generated by Django 3.2.10 on 2023-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_course_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='main_image',
            field=models.ImageField(blank=True, default='defautl_course_image.png', upload_to='', verbose_name='Изображение курса'),
        ),
    ]
