# Generated by Django 3.2.10 on 2023-01-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_course_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AlterModelOptions(
            name='school_courses',
            options={'verbose_name': 'Курс в школе', 'verbose_name_plural': 'Курсы в школах'},
        ),
        migrations.RenameField(
            model_name='school_courses',
            old_name='Course',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='main_image',
            field=models.ImageField(default='defautl_course_image.png', upload_to='', verbose_name='Изображение курса'),
        ),
    ]
