# Generated by Django 3.2.10 on 2023-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20230128_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
    ]
